<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK6xd4la\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK6xd4la/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK6xd4la.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK6xd4la\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK6xd4la\App_KernelDevDebugContainer([
    'container.build_hash' => 'K6xd4la',
    'container.build_id' => '1a8fb649',
    'container.build_time' => 1606850885,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK6xd4la');
